### PR TITLE
factorio.moon-logic v2 patchwork

### PR DESCRIPTION
**Pull request by anonhostpi**
Using https://gist.github.com/tburrows13/687f7dc86da1840624575ba437e86cfa as a guide

WIP

### CODE REVIEW

**Comment by mk-fg** [comment]
Thanks, but I can't test those, and don't want to maintain the mod if I don't even play/have the game tbh.

So I think all these changes might as well exist in your fork of the mod, and you can easily publish new version (probably under less stupid name too) on factorio mod portal - just copy Description/FAQ from .md files in this repo, and it should be in exactly same place as this mod was.

You won't have any friction of having me to needlessly "approve" changes that way, esp. since it's pointless as mentioned if I don't test or even look at them anyway, and it won't be any work for me to worry about any of this either, of course :)

If you'll end up forking the mod that way, let me know - I'll link to it in the Moon Logic one's description.
Best of luck making it work either way, don't think it should be any more difficult than a couple tweaks like that.

**Comment by anonhostpi** [comment]
will maintain course for now, then move the patch into its own independent repo

**Comment by anonhostpi** [comment]
You have any insight on this:

https://github.com/anonhostpi/mk-fg-games/issues/1

strict_mode_enable is throwing when the `global` variable is used in `update_signal_types_table`

EDIT: I think I figured it out...

**Comment by anonhostpi** [comment]
Ok I did. [`global` has been renamed to `storage`](https://gist.github.com/tburrows13/687f7dc86da1840624575ba437e86cfa#global---storage) and storage is not a key on _ENV. I will just have to patch out every call to `global` with `storage`

**Comment by anonhostpi** [comment]
I've finally made it into a save game, but it is still erroring out. Got more work to do... damn it 😭😭😭

**Comment by mk-fg** [comment]
Given that devs seem to have renamed a bunch of stuff, suspect if you wait a bit, someone will write a (rather simple) script to point out all places where old names are used, which might be easier than to hunt down them all when they're used at runtime in a dynamic language like Lua.
Though then again, not rocket science either, will probably catch 95% of issues on a basic first run.

**Comment by anonhostpi** [comment]
That's alright. If I'm going to maintain this, its better that I get familiar with the nuances anyway.

**Comment by anonhostpi** [comment]
but I will say that this is ridiculous lol:

see: https://github.com/mk-fg/games/compare/master...anonhostpi:mk-fg-games:master

**Pull request closed without merging**
